version: "3.9"

services:

  mess-cli-uvicorn:
    image: mess-cli:1.0
    restart: always
    depends_on:
      - mess-cli-redis
    ports:
      - "8000:8000"
  mess-cli-redis:
    image: redis:7.0.2-alpine3.16
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data:
